### ISSUE TITLE
update

### ISSUE THREAD

**Issue by LucasB25** [a3pire/musicard#1]
![image](https://github.com/A3PIRE/musicard/assets/50886682/cbd4c555-ebee-4365-bd07-ad33e75c22f3)
![image](https://github.com/A3PIRE/musicard/assets/50886682/2f20108d-eaff-490c-a97a-43704fe546d8)

you could improve the paternity with more information as in the screen?

**Comment by A3PIRE** [comment]
Using another font will change the position of text in maximum cases.
In the Musicard package, you have better customizable options.
In the future, I will add more templates and designs.
