### ISSUE TITLE
Problem starting the bot.

### ISSUE THREAD

**Issue by ZenoXTV** [a3pire/musicard#4]
Hello, I'd like to report a bug I've had for a few hours now. When I start my bot with the musicard module, it displays this error.
I tried without the module what it was doing, and it didn't show me this error. Thank you for your help and have a nice day.

```Error loading poru event: 
Error: ENOENT: no such file or directory, lstat 'C:\Users\%%%\%%%\Project\res

**Comment by UnschooledGamer** [comment]
I have Created a pull request (can be found up) to fix this issue do tell me if it fixes your issue.

**Comment by flam3face** [comment]
@ZenoXTV We are sorry for our mistake. By the way,  the problem is fixed; just install the **musicard** package again.
