### ISSUE TITLE
The text cannot be used for text other than the English text

### ISSUE THREAD

**Issue by AsameJP** [a3pire/musicard#7]
I have created a Discord Bot that allows users to select songs using Slash Commands. Most of my friends are from Japan and Korea. When my friends enter song titles into the bot, they appear as garbled characters similar to not supporting special characters. However, artist names still appear in the English language. I apologize for not having much knowledge about coding, and I'm wondering what steps I should take to address this issue.

- Translate by ChatGPT

**Comment by KBYSHanahira** [comment]
Same

**Comment by KBYSHanahira** [comment]
@AsameJP , I'm resolve it by use font type ".otf" to fix this

fix in directory :  ```node_modules/musicard/res/< - You font files ->.otf```

and fix code in : ```node_modules/musicard/build/index.d.ts```

from : ``` canvas.GlobalFonts.registerFromPath(`${devmod ? "" : "node_modules/musicard/"}res/momcakebold.ttf`, 'momcakebold'); ```

to : ```canvas.GlobalFonts.registerFromPath(`${devmod ? "" : "node_modules/musicard/"}res/< - You font file - >.otf`, 'momcakebold');```

Result : 
![image](https://github.com/a3pire/musicard/assets/85464400/ff83d2bc-ae4d-4b4d-a398-76ff3f0851aa)

Have Fun :)

**Comment by flam3face** [comment]
Added language support in **1.4.2**
